/**
 * Payments
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.swisscom.api.sdk.payments.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * PaymentRequestPayerId
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-03-30T10:17:02.666+02:00")
public class PaymentRequestPayerId   {
  @SerializedName("billingProfile")
  private String billingProfile = null;

  /**
   * Prefers a billing profile with a product of type specified.
   */
  public enum PreferredProductTypeEnum {
    @SerializedName("wireless")
    WIRELESS("wireless"),
    
    @SerializedName("landline")
    LANDLINE("landline"),
    
    @SerializedName("tv")
    TV("tv");

    private String value;

    PreferredProductTypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("preferredProductType")
  private PreferredProductTypeEnum preferredProductType = null;

  @SerializedName("scn")
  private String scn = null;

  public PaymentRequestPayerId billingProfile(String billingProfile) {
    this.billingProfile = billingProfile;
    return this;
  }

   /**
   * The billing profile identifier.
   * @return billingProfile
  **/
  @ApiModelProperty(example = "BSC:BAC:1151294", value = "The billing profile identifier.")
  public String getBillingProfile() {
    return billingProfile;
  }

  public void setBillingProfile(String billingProfile) {
    this.billingProfile = billingProfile;
  }

  public PaymentRequestPayerId preferredProductType(PreferredProductTypeEnum preferredProductType) {
    this.preferredProductType = preferredProductType;
    return this;
  }

   /**
   * Prefers a billing profile with a product of type specified.
   * @return preferredProductType
  **/
  @ApiModelProperty(example = "landline", value = "Prefers a billing profile with a product of type specified.")
  public PreferredProductTypeEnum getPreferredProductType() {
    return preferredProductType;
  }

  public void setPreferredProductType(PreferredProductTypeEnum preferredProductType) {
    this.preferredProductType = preferredProductType;
  }

  public PaymentRequestPayerId scn(String scn) {
    this.scn = scn;
    return this;
  }

   /**
   * The Swisscom customer identification number.
   * @return scn
  **/
  @ApiModelProperty(example = "84441263", value = "The Swisscom customer identification number.")
  public String getScn() {
    return scn;
  }

  public void setScn(String scn) {
    this.scn = scn;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentRequestPayerId paymentRequestPayerId = (PaymentRequestPayerId) o;
    return Objects.equals(this.billingProfile, paymentRequestPayerId.billingProfile) &&
        Objects.equals(this.preferredProductType, paymentRequestPayerId.preferredProductType) &&
        Objects.equals(this.scn, paymentRequestPayerId.scn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(billingProfile, preferredProductType, scn);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentRequestPayerId {\n");
    
    sb.append("    billingProfile: ").append(toIndentedString(billingProfile)).append("\n");
    sb.append("    preferredProductType: ").append(toIndentedString(preferredProductType)).append("\n");
    sb.append("    scn: ").append(toIndentedString(scn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

